// Code generated by protoc-gen-go. DO NOT EDIT.
// source: webhookForwarder.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListOfString struct {
	Entry                []string `protobuf:"bytes,1,rep,name=entry,proto3" json:"entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOfString) Reset()         { *m = ListOfString{} }
func (m *ListOfString) String() string { return proto.CompactTextString(m) }
func (*ListOfString) ProtoMessage()    {}
func (*ListOfString) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb94b81c6a7ef5b8, []int{0}
}

func (m *ListOfString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOfString.Unmarshal(m, b)
}
func (m *ListOfString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOfString.Marshal(b, m, deterministic)
}
func (m *ListOfString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOfString.Merge(m, src)
}
func (m *ListOfString) XXX_Size() int {
	return xxx_messageInfo_ListOfString.Size(m)
}
func (m *ListOfString) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOfString.DiscardUnknown(m)
}

var xxx_messageInfo_ListOfString proto.InternalMessageInfo

func (m *ListOfString) GetEntry() []string {
	if m != nil {
		return m.Entry
	}
	return nil
}

type SubscribeRequest struct {
	Origin               string   `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb94b81c6a7ef5b8, []int{1}
}

func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest.Unmarshal(m, b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(m, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest.Size(m)
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

func (m *SubscribeRequest) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

type WebhookCall struct {
	Origin               string                   `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Method               string                   `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Uri                  string                   `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	Headers              map[string]*ListOfString `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte                   `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *WebhookCall) Reset()         { *m = WebhookCall{} }
func (m *WebhookCall) String() string { return proto.CompactTextString(m) }
func (*WebhookCall) ProtoMessage()    {}
func (*WebhookCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb94b81c6a7ef5b8, []int{2}
}

func (m *WebhookCall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebhookCall.Unmarshal(m, b)
}
func (m *WebhookCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebhookCall.Marshal(b, m, deterministic)
}
func (m *WebhookCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebhookCall.Merge(m, src)
}
func (m *WebhookCall) XXX_Size() int {
	return xxx_messageInfo_WebhookCall.Size(m)
}
func (m *WebhookCall) XXX_DiscardUnknown() {
	xxx_messageInfo_WebhookCall.DiscardUnknown(m)
}

var xxx_messageInfo_WebhookCall proto.InternalMessageInfo

func (m *WebhookCall) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *WebhookCall) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *WebhookCall) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *WebhookCall) GetHeaders() map[string]*ListOfString {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *WebhookCall) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*ListOfString)(nil), "webhookForwarder.ListOfString")
	proto.RegisterType((*SubscribeRequest)(nil), "webhookForwarder.SubscribeRequest")
	proto.RegisterType((*WebhookCall)(nil), "webhookForwarder.WebhookCall")
	proto.RegisterMapType((map[string]*ListOfString)(nil), "webhookForwarder.WebhookCall.HeadersEntry")
}

func init() { proto.RegisterFile("webhookForwarder.proto", fileDescriptor_bb94b81c6a7ef5b8) }

var fileDescriptor_bb94b81c6a7ef5b8 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0x4f, 0x4b, 0xc3, 0x30,
	0x1c, 0x25, 0xed, 0x36, 0xd9, 0xaf, 0x3d, 0x94, 0x20, 0x23, 0x0c, 0x94, 0x52, 0x3c, 0x94, 0x1d,
	0x8a, 0x54, 0x0f, 0xe2, 0xd1, 0x7f, 0x78, 0x10, 0x94, 0xec, 0x30, 0xd8, 0xad, 0xb1, 0x71, 0x0d,
	0xab, 0xcd, 0x4c, 0x53, 0x47, 0x3f, 0x80, 0xdf, 0x5b, 0xda, 0x4c, 0x29, 0x2d, 0x7a, 0x7b, 0xef,
	0xf1, 0xda, 0xf7, 0x7e, 0x2f, 0x30, 0xdb, 0x73, 0x96, 0x49, 0xb9, 0x7d, 0x90, 0x6a, 0x9f, 0xa8,
	0x94, 0xab, 0x68, 0xa7, 0xa4, 0x96, 0xd8, 0xeb, 0xeb, 0xc1, 0x19, 0xb8, 0x4f, 0xa2, 0xd4, 0xcf,
	0x6f, 0x4b, 0xad, 0x44, 0xb1, 0xc1, 0xc7, 0x30, 0xe6, 0x85, 0x56, 0x35, 0x41, 0xbe, 0x1d, 0x4e,
	0xa9, 0x21, 0xc1, 0x02, 0xbc, 0x65, 0xc5, 0xca, 0x57, 0x25, 0x18, 0xa7, 0xfc, 0xa3, 0xe2, 0xa5,
	0xc6, 0x33, 0x98, 0x48, 0x25, 0x36, 0xa2, 0x20, 0xc8, 0x47, 0xe1, 0x94, 0x1e, 0x58, 0xf0, 0x65,
	0x81, 0xb3, 0x32, 0x31, 0xb7, 0x49, 0x9e, 0xff, 0xe5, 0x6b, 0xf4, 0x77, 0xae, 0x33, 0x99, 0x12,
	0xcb, 0xe8, 0x86, 0x61, 0x0f, 0xec, 0x4a, 0x09, 0x62, 0xb7, 0x62, 0x03, 0xf1, 0x1d, 0x1c, 0x65,
	0x3c, 0x49, 0xb9, 0x2a, 0xc9, 0xc8, 0xb7, 0x43, 0x27, 0x5e, 0x44, 0x83, 0xfb, 0x3a, 0x89, 0xd1,
	0xa3, 0x31, 0xdf, 0x37, 0xd5, 0xe9, 0xcf, 0xa7, 0x18, 0xc3, 0x88, 0xc9, 0xb4, 0x26, 0x63, 0x1f,
	0x85, 0x2e, 0x6d, 0xf1, 0x7c, 0x0d, 0x6e, 0xd7, 0xdc, 0x64, 0x6f, 0x79, 0x7d, 0x28, 0xda, 0x40,
	0x7c, 0x09, 0xe3, 0xcf, 0x24, 0xaf, 0x78, 0x5b, 0xd2, 0x89, 0x4f, 0x87, 0xc9, 0xdd, 0xf9, 0xa8,
	0x31, 0x5f, 0x5b, 0x57, 0x28, 0x4e, 0xc1, 0x5b, 0xf5, 0xbc, 0xf8, 0x05, 0xa6, 0xbf, 0x3b, 0xe2,
	0x60, 0xf8, 0xaf, 0xfe, 0xc8, 0xf3, 0x93, 0x7f, 0x2f, 0x3d, 0x47, 0x37, 0xa3, 0xb5, 0xb5, 0x63,
	0x6c, 0xd2, 0x3e, 0xef, 0xc5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5e, 0x77, 0xe6, 0xc3, 0xf8,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WebhookForwarderClient is the client API for WebhookForwarder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WebhookForwarderClient interface {
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (WebhookForwarder_SubscribeClient, error)
}

type webhookForwarderClient struct {
	cc *grpc.ClientConn
}

func NewWebhookForwarderClient(cc *grpc.ClientConn) WebhookForwarderClient {
	return &webhookForwarderClient{cc}
}

func (c *webhookForwarderClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (WebhookForwarder_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_WebhookForwarder_serviceDesc.Streams[0], "/webhookForwarder.WebhookForwarder/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &webhookForwarderSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WebhookForwarder_SubscribeClient interface {
	Recv() (*WebhookCall, error)
	grpc.ClientStream
}

type webhookForwarderSubscribeClient struct {
	grpc.ClientStream
}

func (x *webhookForwarderSubscribeClient) Recv() (*WebhookCall, error) {
	m := new(WebhookCall)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WebhookForwarderServer is the server API for WebhookForwarder service.
type WebhookForwarderServer interface {
	Subscribe(*SubscribeRequest, WebhookForwarder_SubscribeServer) error
}

// UnimplementedWebhookForwarderServer can be embedded to have forward compatible implementations.
type UnimplementedWebhookForwarderServer struct {
}

func (*UnimplementedWebhookForwarderServer) Subscribe(req *SubscribeRequest, srv WebhookForwarder_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}

func RegisterWebhookForwarderServer(s *grpc.Server, srv WebhookForwarderServer) {
	s.RegisterService(&_WebhookForwarder_serviceDesc, srv)
}

func _WebhookForwarder_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WebhookForwarderServer).Subscribe(m, &webhookForwarderSubscribeServer{stream})
}

type WebhookForwarder_SubscribeServer interface {
	Send(*WebhookCall) error
	grpc.ServerStream
}

type webhookForwarderSubscribeServer struct {
	grpc.ServerStream
}

func (x *webhookForwarderSubscribeServer) Send(m *WebhookCall) error {
	return x.ServerStream.SendMsg(m)
}

var _WebhookForwarder_serviceDesc = grpc.ServiceDesc{
	ServiceName: "webhookForwarder.WebhookForwarder",
	HandlerType: (*WebhookForwarderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _WebhookForwarder_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "webhookForwarder.proto",
}
